# Generated by Django 3.2.4 on 2022-01-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20220104_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
