# Generated by Django 3.2.4 on 2022-01-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20220104_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.CharField(default='Геморой', max_length=256),
            preserve_default=False,
        ),
    ]
